port: 4000

api-key:
  id: id
  secret: secret

database:
  host: localhost
  database: spelwerk_v5
  username: spelwerk
  password: spelwerk

secrets:
  jwt: jwt
  aes: aes
  sha: sha

salt: 4

superuser:
  email: admin@spelwerk.com
  password: password
  noreply: noreply@spelwerk.com

links:
  base: http://spelwerk.dev/

  user:
    create: /user/create/verify/
    password: /user/password/verify/
    email: /user/email/verify/
    login: /post/login.php?s=

timeouts:
  user:
    verify:
      amount: 7
      time: days

    login:
      amount: 60
      time: minutes

    email:
      amount: 60
      time: minutes

    password:
      amount: 60
      time: minutes