#tableName: pluralName

armour: armours
asset: assets
augmentation: augmentations
attribute: attributes
background: backgrounds
bionic: bionics
corporation: corporations
country: countries
creature: creatures
currency: currencies
epoch: epochs
expertise: expertises
focus: focuses
form: forms
gift: gifts
identity: identities
imperfection: imperfections
language: languages
location: locations
loyalty: loyalties
manifestation: manifestations
milestone: milestones
nature: natures
primal: primals
relation: relations
shield: shields
skill: skills
software: software
species: species
spell: spells
tactic: tactics
wealth: wealth
weaponmod: mods
weapon: weapons
world: worlds