baseline:
  background: 1
  expertise: 10
  form: 1
  gift: 1
  imperfection: 1
  language: 1
  milestone: 1
  primal: 10
  skill: 10
  spell: 10

divide:
  expertise: 5
  milestone: 5
  primal: 5
  skill: 5
  spell: 5

maximum:
  experience: 50
  expertise: 30
  milestone: 4
  primal: 30
  skill: 30
  spell: 30

cost:
  form: 10
  language: 10
  gift: 10
  milestone: 10